modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="astralita"
version="${file.jarVersion}"
displayName="Astralita"
authors="GB"
description='''Astralita: material raro do End superior a Netherite.'''
[[dependencies.astralita]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)";ordering="NONE";side="BOTH"
[[dependencies.astralita]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)";ordering="NONE";side="BOTH"
